# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Test private module

on:
 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.133.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: |
          echo ${{ secrets.GH_PAT }}
      - name: Granting private modules access
        run: |
          git config --global url."https://2b3d4f:${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build
        run: hugo --minify

